### ISSUE TITLE
Les-be-friends addon not working

### ISSUE THREAD

**Issue by naudski** [fr0stxm/addons#1]
Hi,

I tried your repository and saw that this addon isn't working. Maybe you can fix it.
I'm using Kodi 18.6.
When I open the addon it doesn't show any dirs and content. 
Great work by the way!

**Comment by naudski** [comment]
Is there no development anymore on these addons?

**Comment by fr0stxm** [comment]
Yes. 

However. Life and C-19, coupled with a young family took over. When I have chance I'll fix the bugs

**Comment by naudski** [comment]
Completely understandable. Take care!

**Comment by fr0stxm** [comment]
Les-Be-Friends has been fixed 0.2.3 is in the spankbank.cf repo
JFH has also been fixed.
